### ISSUE TITLE
Problem with Capistrano 3.5.0

### ISSUE THREAD

**Issue by aleksejleonov** [phallstrom/slackistrano#48]
Looks like there are problem with new Capistrano 3.5.0.

```
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `config' for #<Capistrano::Configuration:0x007fab951655d8>

Tasks: TOP => deploy:updating => slack:deploy:updating
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `config' for #<Capistrano::Configuration:0x007fab951655d8>

/Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:73:in `block in post': undefined method `config' for #<Capistrano::Configuration:0x007fab951655d8> (NoMethodError)
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:67:in `each'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:67:in `post'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:29:in `block in run'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:29:in `run'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:58:in `run_locally'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/capistrano.rb:29:in `run'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slackistrano-2.0.1/lib/slackistrano/tasks/slack.rake:23:in `block (3 levels) in <top (required)>'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/airbrussh-1.0.1/lib/airbrussh/rake/context.rb:55:in `execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl/task_enhancements.rb:14:in `block in after'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/airbrussh-1.0.1/lib/airbrussh/rake/context.rb:55:in `execute'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl.rb:15:in `invoke'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/dsl/task_enhancements.rb:56:in `exit_deploy_because_of_exception'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/application.rb:73:in `exit_because_of_exception'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:186:in `rescue in standard_exception_handling'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/lib/capistrano/application.rb:14:in `run'
	from /Users/alex/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.5.0/bin/cap:3:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.3.0/bin/cap:22:in `load'
	from /Users/alex/.rbenv/versions/2.3.0/bin/cap:22:in `<main>'
```

**Comment by zstarer** [comment]
https://github.com/phallstrom/slackistrano/pull/47

install his gem and try it.  :)

**Comment by phallstrom** [comment]
Version 3.0.0 has been released to rubygems which addresses the above issue.
